"""empty message

Revision ID: 0403e1b46505
Revises: 1ed826de7a78
Create Date: 2020-04-07 22:32:53.535757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0403e1b46505'
down_revision = '1ed826de7a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts_categorys',
    sa.Column('posts_id', sa.Integer(), nullable=False),
    sa.Column('categorys_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categorys_id'], ['categorys.id'], ),
    sa.ForeignKeyConstraint(['posts_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('posts_id', 'categorys_id')
    )
    op.drop_constraint('categorys_ibfk_1', 'categorys', type_='foreignkey')
    op.drop_column('categorys', 'aid')
    op.add_column('posts', sa.Column('u_id', sa.Integer(), nullable=True))
    op.drop_constraint('posts_ibfk_2', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'user', ['u_id'], ['id'])
    op.drop_column('posts', 'uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_ibfk_2', 'posts', 'user', ['uid'], ['id'])
    op.drop_column('posts', 'u_id')
    op.add_column('categorys', sa.Column('aid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('categorys_ibfk_1', 'categorys', 'posts', ['aid'], ['id'])
    op.drop_table('posts_categorys')
    # ### end Alembic commands ###
