"""empty message

Revision ID: 1ed826de7a78
Revises: 685d91fb9b42
Create Date: 2020-04-07 21:03:54.087500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ed826de7a78'
down_revision = '685d91fb9b42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorys', sa.Column('aid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categorys', 'posts', ['aid'], ['id'])
    op.drop_constraint('posts_ibfk_1', 'posts', type_='foreignkey')
    op.drop_column('posts', 'cid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('cid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('posts_ibfk_1', 'posts', 'categorys', ['cid'], ['id'])
    op.drop_constraint(None, 'categorys', type_='foreignkey')
    op.drop_column('categorys', 'aid')
    # ### end Alembic commands ###
