"""empty message

Revision ID: 4a91f657679b
Revises: 99608cfc4417
Create Date: 2020-04-08 16:49:00.004135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a91f657679b'
down_revision = '99608cfc4417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts_categorys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts_categorys',
    sa.Column('posts_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('categorys_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['categorys_id'], ['categorys.id'], name='posts_categorys_ibfk_1'),
    sa.ForeignKeyConstraint(['posts_id'], ['posts.id'], name='posts_categorys_ibfk_2'),
    sa.PrimaryKeyConstraint('posts_id', 'categorys_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
