"""empty message

Revision ID: 99608cfc4417
Revises: 38a905b5aac6
Create Date: 2020-04-08 16:43:54.353013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99608cfc4417'
down_revision = '38a905b5aac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('c_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'categorys', ['c_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'c_id')
    # ### end Alembic commands ###
