"""empty message

Revision ID: d2bfffef4c08
Revises: 0403e1b46505
Create Date: 2020-04-08 15:35:52.289245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2bfffef4c08'
down_revision = '0403e1b46505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('c_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'categorys', ['c_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'c_id')
    # ### end Alembic commands ###
